### PR TITLE
sorting function and bug correction

### PR DESCRIPTION
**Pull request by daviderud**
- corrected bug: text of labels not anymore out of borders
- added sorting functionality (by name or frequency, ascending or descending)
- table columns resizable

cheers

### CODE REVIEW

**Comment by darauble** [comment]
Hey, as it's going so well, would you mind adding "Edit the Bookmark" by right-clicking it in the spectrum? :D

**Comment by daviderud** [comment]
ahah, yeah actually I tried to do it, but it was bit cumbersome to manage the gui. However now, when you left click, the bookmark gets automatically selected in the list and you can click on the usual "Edit" button directly.
cheers

**Comment by darauble** [comment]
Right, that's really very useful. But in longer lists the bookmark is selected, but might out of view: the action only selects, but does not scroll to it. I am not very familiar with ImGui, so not sure if that's achievable.

**Comment by daviderud** [comment]
yes I noticed, I'll give it a shot (I am not really familiar with ImGui aswell)

**Pull request merged**
